const POSITIONS = [
  {
    id: "1",
    asset: "Sol_SOL",
    side: "short",
    leverage: 5,
    size: 100,
    collateral: 1000,
    pnl: 100,
    entryPrice: 100,
    markPrice: 100,
    liquidationPrice: 100,
  },
  {
    id: "2",
    asset: "Sol_BTC",
    side: "long",
    leverage: 5,
    size: 100,
    collateral: 1000,
    pnl: 100,
    entryPrice: 100,
    markPrice: 100,
    liquidationPrice: 100,
  },
  {
    id: "3",
    asset: "Sol_USDC",
    side: "short",
    leverage: 5,
    size: 100,
    collateral: 1000,
    pnl: 100,
    entryPrice: 100,
    markPrice: 100,
    liquidationPrice: 100,
  },
  {
    id: "4",
    asset: "Sol_ETH",
    side: "long",
    leverage: 5,
    size: 100,
    collateral: 1000,
    pnl: 100,
    entryPrice: 100,
    markPrice: 100,
    liquidationPrice: 100,
  },
] as const;

export { POSITIONS };
