const POSITIONS = [
  {
    id: "1",
    token: {
      account: "1",
      symbol: "Token 1",
      network: "Solana",
      uri: "https://placeholder.com/16x16",
    },
    side: "short",
    leverage: 5,
    size: 100,
    collateral: 1000,
    pnl: 100,
    entryPrice: 100,
    markPrice: 100,
    liquidationPrice: 100,
  },
  {
    id: "2",
    token: {
      account: "2",
      symbol: "Token 2",
      network: "Solana",
      uri: "https://placeholder.com/16x16",
    },
    side: "long",
    leverage: 5,
    size: 100,
    collateral: 1000,
    pnl: 100,
    entryPrice: 100,
    markPrice: 100,
    liquidationPrice: 100,
  },
  {
    id: "3",
    token: {
      account: "3",
      symbol: "Token 3",
      network: "Solana",
      uri: "https://placeholder.com/16x16",
    },
    side: "short",
    leverage: 5,
    size: 100,
    collateral: 1000,
    pnl: 100,
    entryPrice: 100,
    markPrice: 100,
    liquidationPrice: 100,
  },
  {
    id: "4",
    token: {
      account: "4",
      symbol: "Token 4",
      network: "Solana",
      uri: "https://placeholder.com/16x16",
    },
    side: "long",
    leverage: 5,
    size: 100,
    collateral: 1000,
    pnl: 100,
    entryPrice: 100,
    markPrice: 100,
    liquidationPrice: 100,
  },
] as const;

export { POSITIONS };
