const HISTORY = [
  {
    id: "1",
    txHash: "1",
    token: {
      account: "1",
      symbol: "Token 1",
      network: "Solana",
      uri: "https://placeholder.com/16x16",
    },
    type: "open",
    side: "short",
    leverage: 5,
    pnl: 100,
    price: 100,
    fee: 100,
    time: 100,
  },
  {
    id: "2",
    txHash: "2",
    token: {
      account: "2",
      symbol: "Token 2",
      network: "Solana",
      uri: "https://placeholder.com/16x16",
    },
    type: "close",
    side: "long",
    leverage: 5,
    pnl: 100,
    price: 100,
    fee: 100,
    time: 100,
  },
  {
    id: "3",
    txHash: "3",
    token: {
      account: "3",
      symbol: "Token 3",
      network: "Solana",
      uri: "https://placeholder.com/16x16",
    },
    type: "open",
    side: "short",
    leverage: 5,
    pnl: 100,
    price: 100,
    fee: 100,
    time: 100,
  },
  {
    id: "4",
    txHash: "4",
    token: {
      account: "4",
      symbol: "Token 4",
      network: "Solana",
      uri: "https://placeholder.com/16x16",
    },
    type: "close",
    side: "long",
    leverage: 5,
    pnl: 100,
    price: 100,
    fee: 100,
    time: 100,
  },
];

export { HISTORY };
